### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by dgauche** [ptc-iot-sharing/ThingworxVSCodeProject#12]
I am getting an error building

[21:27:44] Using gulpfile ~/ThingworxVSCodeProject-master/gulpfile.js
[21:27:44] Starting 'build'...
[21:27:44] Starting 'clean'...
[21:27:44] Finished 'clean' after 7.92 ms
[21:27:44] Starting 'build'...
src/MyThing.ts(137,82): error TS2322: Type '"LinkedList"' is not assignable to type '"LicenseGroupUsageDataShape" | "DTAuditShape" | "DesignTimePermissions" | "EntityReferenceWithDescription" | "UserProvisioningUserExclusionList" | "AnalyticsSignalsResult" | ... 324 more ... | undefined'.
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
[21:27:48] 'build' errored after 4.29 s
[21:27:48] Error: TypeScript: Compilation failed
    at Output.mightFinish (/Users/duan/ThingworxVSCodeProject-master/node_modules/gulp-typescript/release/output.js:131:43)
    at /Users/duan/ThingworxVSCodeProject-master/node_modules/gulp-typescript/release/output.js:66:22
[21:27:48] 'build' errored after 4.3 s

**Comment by dgauche** [comment]
I see this was a duplicate.
